#!/usr/bin/env python3
"""Pre-flight for the sweep. Two modes.

  --offline   everything that needs no GPU and no transformers: prep
              determinism, split integrity, run-identity behaviour, scoring
              maths, environment capture, and the contract checker itself.
              Run this on the laptop before touching Colab.

  (default)   the above, then ONE real short training run on the smallest cell
              with ModernBERT-base and 1 epoch, and a contract check of the
              record it produced. Run this on Colab before launching the sweep,
              so a crash costs a minute rather than an hour.

Every check prints PASS or FAIL and the script exits nonzero on any FAIL.
"""
import argparse, json, os, sys, tempfile, shutil, subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
EXP = os.path.normpath(os.path.join(HERE, '..'))
sys.path.insert(0, HERE)

FAILED = []


def check(name, cond, detail=''):
    ok = bool(cond)
    print(f"  {'PASS' if ok else 'FAIL'}  {name}{'  ' + detail if detail else ''}")
    if not ok:
        FAILED.append(name)
    return ok


def offline(exp=EXP):
    import report, metrics, env_capture, contract

    print('\n== prep: determinism and integrity ==')
    docs_p, splits_p = f'{exp}/docs.jsonl', f'{exp}/splits.json'
    card_p = f'{exp}/dataset_card.json'
    if not os.path.exists(docs_p):
        check('prep outputs exist', False, '(run prep.py first)')
        return
    card = json.load(open(card_p))
    S = json.load(open(splits_p))
    docs = {d['doc_id']: d for d in map(json.loads, open(docs_p))}

    import hashlib
    live = hashlib.sha256(open(docs_p, 'rb').read()).hexdigest()
    check('docs.jsonl matches its dataset_card hash', live == card['docs_sha256'])

    # Determinism is tested against a FROZEN COPY of the corpus, not the live one.
    # The corpus is generated by another process and grows while this runs; a
    # rebuild that differed because the input moved would be a false alarm, and a
    # rebuild that matched a moving input would be a false pass.
    sys.path.insert(0, exp)
    import importlib
    prep = importlib.import_module('prep')
    tmp = tempfile.mkdtemp()
    try:
        snap = f'{tmp}/corpus'
        os.makedirs(snap)
        for f in ('dataset.jsonl', 'train.jsonl', 'dev.jsonl', 'test.jsonl'):
            src = f'{prep.CORPUS}/{f}'
            if os.path.exists(src):
                shutil.copy(src, f'{snap}/{f}')
        a, b = f'{tmp}/a', f'{tmp}/b'
        os.makedirs(a); os.makedirs(b)
        prep.build(corpus=snap, out=a)
        prep.build(corpus=snap, out=b)
        ca = json.load(open(f'{a}/dataset_card.json'))
        cb = json.load(open(f'{b}/dataset_card.json'))
        check('prep.py is deterministic (docs)', ca['docs_sha256'] == cb['docs_sha256'],
              f"{ca['docs_sha256_short']} vs {cb['docs_sha256_short']}")
        check('prep.py is deterministic (splits)',
              ca['splits_sha256'] == cb['splits_sha256'])
        check('prep.py is deterministic (cell membership)',
              json.load(open(f'{a}/splits.json')) == json.load(open(f'{b}/splits.json')))
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    # Separately: has the live corpus moved since docs.jsonl was built? Not a
    # failure -- the corpus is still generating -- but prep.py must be re-run
    # before any run whose numbers are meant to be reported.
    live_corpus = hashlib.sha256(
        open(f'{prep.CORPUS}/dataset.jsonl', 'rb').read()).hexdigest()[:16]
    check('docs.jsonl was built from the corpus that is on disk right now',
          live_corpus == card['corpus_dataset_sha256_short'],
          f"{card['corpus_dataset_sha256_short']} vs {live_corpus}")
    check('the corpus is complete', card['complete'] is True)
    check('every generator is within 6% of the human median length',
          all(abs(v - 1.0) <= 0.06 for g, v in card['words_ratio_to_human_median'].items()),
          str({g: v for g, v in card['words_ratio_to_human_median'].items()
               if abs(v - 1.0) > 0.06}))
    check('human and AI documents are paired 1:1',
          card['n_docs'] == 2 * card['n_questions'])

    check('normalisation removes every newline', card['norm_removes_all_newlines'])
    check('every generator appears in the test split',
          all(s.get('test', 0) > 0 for s in card['generator_x_split'].values()),
          str({g: s.get('test', 0) for g, s in card['generator_x_split'].items()}))

    print('\n== splits: leakage ==')
    leaks = []
    for c in S['cells']:
        q = {k: {docs[i]['q_id'] for i in c[k]} for k in ('train_ids', 'val_ids', 'test_ids')}
        if q['train_ids'] & q['test_ids'] or q['train_ids'] & q['val_ids'] \
                or q['val_ids'] & q['test_ids']:
            leaks.append(c['cell'])
        if c['heldout_generator']:
            seen = {docs[i]['generator'] for i in c['train_ids'] + c['val_ids']}
            if c['heldout_generator'] in seen:
                leaks.append(c['cell'] + ':heldout-seen')
    check('no question straddles a split in any cell', not leaks, str(leaks[:3]))
    check('every LOGO test set is exactly held-out generator + humans',
          all({docs[i]['generator'] for i in c['test_ids']}
              == {'HUMAN', c['heldout_generator']}
              for c in S['cells'] if c['heldout_generator']))
    check('human and AI answer of a question always share a split',
          all(len({docs[f'hu-{docs[i]["item_id"]}']['split'], docs[i]['split']}) == 1
              for i in docs if i.startswith('ai-')))

    print('\n== run identity ==')
    cell = S['cells'][0]
    hp = {'lr': 3e-5, 'batch': 8, 'max_epochs': 3, 'weight_decay': 8e-6, 'max_length': 2048}
    _, h1 = report.run_key(cell, 0, 0, 'm', 'cls', True, hp)
    _, h2 = report.run_key(cell, 0, 0, 'm', 'cls', True, dict(hp))
    check('run key is stable for an identical run', h1 == h2)
    variants = {
        'data seed': report.run_key(cell, 0, 1, 'm', 'cls', True, hp)[1],
        'init seed': report.run_key(cell, 1, 0, 'm', 'cls', True, hp)[1],
        'pooling': report.run_key(cell, 0, 0, 'm', 'mean', True, hp)[1],
        'gradient checkpointing': report.run_key(cell, 0, 0, 'm', 'cls', False, hp)[1],
        'lr': report.run_key(cell, 0, 0, 'm', 'cls', True, hp | {'lr': 2e-5})[1],
        'model': report.run_key(cell, 0, 0, 'n', 'cls', True, hp)[1],
        'cell': report.run_key(S['cells'][2], 0, 0, 'm', 'cls', True, hp)[1],
    }
    for what, h in variants.items():
        check(f'run key changes when {what} changes', h != h1)

    print('\n== warm-start bookkeeping ==')
    tmp2 = tempfile.mkdtemp()
    try:
        check('no checkpoint dir means a cold start',
              report.latest_checkpoint(f'{tmp2}/nope') is None)
        run_dir = f'{tmp2}/abc123'
        for step in (100, 900, 200):
            os.makedirs(f'{run_dir}/checkpoint-{step}')
            open(f'{run_dir}/checkpoint-{step}/trainer_state.json', 'w').write('{}')
        check('warm start picks the highest step, not the newest mtime',
              report.latest_checkpoint(run_dir).endswith('checkpoint-900'))
        os.makedirs(f'{run_dir}/checkpoint-1200')          # no trainer_state.json
        check('a half-written checkpoint is ignored',
              report.latest_checkpoint(run_dir).endswith('checkpoint-900'))
        check('the checkpoint dir is named by run identity, so a warm start cannot '
              'resume a different recipe',
              report.run_key(cell, 0, 0, 'm', 'cls', True, hp)[1]
              != report.run_key(cell, 0, 0, 'm', 'cls', False, hp)[1])
        check('the checkpoint-selection metric is inside the run key',
              report.run_key(cell, 0, 0, 'm', 'cls', True, hp | {'select_metric': 'loss'})[1]
              != report.run_key(cell, 0, 0, 'm', 'cls', True, hp | {'select_metric': 'auc'})[1])
        check('early-stopping patience is inside the run key',
              report.run_key(cell, 0, 0, 'm', 'cls', True,
                             hp | {'early_stop_patience_evals': None})[1]
              != report.run_key(cell, 0, 0, 'm', 'cls', True,
                                hp | {'early_stop_patience_evals': 3})[1])
        check('checkpoint cadence is inside the run key (it changes best-step selection)',
              report.run_key(cell, 0, 0, 'm', 'cls', True, hp | {'ckpt_steps': 100})[1]
              != report.run_key(cell, 0, 0, 'm', 'cls', True, hp | {'ckpt_steps': 250})[1])
    finally:
        shutil.rmtree(tmp2, ignore_errors=True)

    print('\n== scoring maths ==')
    p = [0.9, 0.8, 0.7, 0.2, 0.1, 0.05]
    lab = ['ai', 'ai', 'ai', 'human', 'human', 'human']
    r = report.binary_report(p, lab, 0.5)
    check('perfect separation scores AUC 1.0', r['auc'] == 1.0)
    check('recall and specificity both 1.0 at 0.5',
          r['recall_ai'] == 1.0 and r['specificity'] == 1.0)
    rr = report.binary_report([0.5]*6, lab, 0.5)
    check('all-tied scores give AUC 0.5', rr['auc'] == 0.5)
    check('AUC is invariant to threshold', report.binary_report(p, lab, 0.9)['auc'] == 1.0)
    check('accuracy drops when the threshold excludes true positives',
          report.binary_report(p, lab, 0.85)['recall_ai'] < 1.0)
    t, ba = report.best_threshold(p, lab)
    check('dev-chosen threshold finds the perfect split', ba == 1.0, f't={t}')
    check('one-class input returns no AUC rather than a wrong number',
          report.binary_report([0.9, 0.8], ['ai', 'ai'], 0.5)['auc'] is None)

    print('\n== JSON serialisability ==')
    # A record that cannot serialise fails AFTER training has finished and been
    # paid for. Feed the scoring path numpy scalars, exactly as a softmax does.
    import numpy as _np
    pn = [_np.float32(x) for x in (0.9, 0.8, 0.7, 0.2, 0.1, 0.05)]
    ln = ['ai', 'ai', 'ai', 'human', 'human', 'human']
    rn = report.binary_report(pn, ln, _np.float32(0.5))
    tn, ban = report.best_threshold(pn, ln)
    for nm, val in (('binary_report output', rn), ('dev-chosen threshold', tn),
                    ('dev balanced accuracy', ban),
                    ('probs block', {'d1': [float(x) for x in _np.float32([0.1, 0.9])]})):
        try:
            json.dumps(val)
            ok = True
        except TypeError:
            ok = False
        check(f'{nm} is JSON-serialisable given numpy inputs', ok, repr(val)[:80])
    check('binary_report returns no numpy scalars (counts stay ints, rates floats)',
          not any(isinstance(v, _np.generic) for v in rn.values())
          and all(type(rn[k]) is int for k in ('n', 'n_ai', 'n_human'))
          and all(type(rn[k]) is float for k in ('auc', 'balanced_acc', 'recall_ai')))

    print('\n== environment capture ==')
    env = env_capture.snapshot(code_paths=[f'{HERE}/{f}' for f in
                                           ('train_cell.py', 'metrics.py', 'env_capture.py')])
    check('pip freeze captured', len(env['pip_freeze']) > 10, f"{len(env['pip_freeze'])} pkgs")
    check('python version captured', bool(env['python_version_short']))
    check('torch version captured', bool(env['libraries']['torch']))
    check('numerics flags captured', 'cuda_matmul_allow_tf32' in env['torch_flags'])
    check('code fingerprint captured', bool(env['code']['_combined']))
    check('env hash is stable across calls (nvidia-smi noise excluded)',
          env['env_hash'] == env_capture.snapshot(
              code_paths=[f'{HERE}/{f}' for f in
                          ('train_cell.py', 'metrics.py', 'env_capture.py')])['env_hash'])

    print('\n== the contract checker itself ==')
    good = _synthetic_record()
    hard, _ = contract.check(good)
    check('a complete record passes the contract', not hard, str(hard[:2]))
    for clause, mutate in (
            ('pip freeze', lambda r: r['env'].__setitem__('pip_freeze', [])),
            ('per-document probabilities', lambda r: r.__setitem__('probs', {})),
            ('per-generator results', lambda r: r.__setitem__('per_generator', {})),
            ('data-order seed', lambda r: r['seeds'].pop('data_order')),
            ('gradient checkpointing', lambda r: r['code_path'].pop('gradient_checkpointing')),
            ('GPU model', lambda r: r['env']['gpu'].pop('name')),
            ('full-state checkpointing',
             lambda r: r['code_path']['checkpointing'].__setitem__('full_state', False)),
            ('resume provenance', lambda r: r['code_path'].pop('resumed_from_checkpoint')),
            ('early-stopping semantics',
             lambda r: r['code_path']['early_stopping'].pop('patience_evals')),
            ('checkpoint selection metric',
             lambda r: r['code_path']['checkpoint_selection'].pop('metric')),
            ('docs hash', lambda r: r['data'].pop('docs_sha256'))):
        bad = json.loads(json.dumps(good))
        mutate(bad)
        h, s = contract.check(bad)
        check(f'contract catches a record missing: {clause}',
              clause in [x[0] for x in h + s])


def _synthetic_record():
    """A record with every contract clause satisfied. Used only to test the
    checker -- it must reject mutations of this, and accept this."""
    return {
        'cell': 'binary|norm', 'classes': ['human', 'ai'], 'n': {'test': 2},
        'seeds': {'weight_init': 0, 'data_order': 0},
        'hp': {'lr': 3e-5, 'batch': 8, 'max_epochs': 3, 'weight_decay': 8e-6,
               'max_length': 2048},
        'data': {'docs_sha256': 'a'*64, 'splits_sha256': 'b'*64,
                 'cell_id_hashes': {'train_ids': 'x', 'val_ids': 'y', 'test_ids': 'z'}},
        'code_path': {'gradient_checkpointing': True, 'attn_implementation': 'sdpa',
                      'reference_compile': False, 'classifier_pooling': 'cls',
                      'precision': 'bf16', 'resumed_from_checkpoint': None,
                      'checkpoint_selection': {'metric': 'eval_loss',
                                               'greater_is_better': False},
                      'early_stopping': {'patience_evals': 53, 'can_fire': False,
                                         'total_evals_possible': 52,
                                         'unit': 'evaluations'},
                      'checkpointing': {'strategy': 'steps', 'every_steps': 100,
                                        'full_state': True, 'save_total_limit': 2}},
        'env': {'pip_freeze': ['torch==2.6.0'] * 20, 'python_version_short': '3.11.0',
                'env_hash': 'deadbeef',
                'libraries': {'torch': '2.6.0', 'transformers': '5.15.1',
                              'torch_cuda': '12.4', 'torch_cudnn': 90100},
                'gpu': {'name': 'NVIDIA L4', 'driver_version': '550.54.15'},
                'torch_flags': {'cuda_matmul_allow_tf32': False},
                'code': {'_combined': 'cafe1234'}},
        'tokenisation': {'test': {'truncated_frac': 0.0}},
        'epochs_run': 3.0,
        'test': {'auc': 0.9},
        'probs': {'d1': [0.1, 0.9], 'd2': [0.8, 0.2]},
        'per_generator': {'x-ai/grok-4.6': {'auc': 0.9}},
    }


def gpu_run(exp=EXP, model='answerdotai/ModernBERT-base'):
    """One real, short run. Proves the training path executes and that what it
    writes satisfies the contract -- before an hour of sweep depends on it."""
    print(f'\n== one real training run ({model}, 1 epoch, smallest cell) ==')
    out = f'{exp}/results/smoke_results.jsonl'
    if os.path.exists(out):
        os.remove(out)
    S = json.load(open(f'{exp}/splits.json'))
    cell = min((c for c in S['cells'] if c['text_field'] == 'text_norm'),
               key=lambda c: c['n']['train_ids'])['cell']
    cmd = [sys.executable, f'{HERE}/train_cell.py',
           '--docs', f'{exp}/docs.jsonl', '--splits', f'{exp}/splits.json',
           '--card', f'{exp}/dataset_card.json', '--out', out,
           '--envdir', f'{exp}/env', '--workdir', '/tmp/smoke_work',
           '--model', model, '--cells', cell, '--text', 'norm',
           '--init-seeds', '0', '--epochs', '1', '--limit', '1']
    print('  $ ' + ' '.join(cmd), flush=True)
    fails = out.replace('.jsonl', '_failures.jsonl')
    if os.path.exists(fails):
        os.remove(fails)
    p = subprocess.run(cmd)
    if not check('training run completed', p.returncode == 0):
        return
    # train_cell.py deliberately exits 0 on a failed run so one bad cell cannot
    # abort a sweep. The smoke test must therefore read the failures file, not
    # the exit status.
    nfail = sum(1 for _ in open(fails)) if os.path.exists(fails) else 0
    if not check('no run recorded a failure', nfail == 0,
                 open(fails).read()[:300] if nfail else ''):
        return
    check('a record was written', os.path.exists(out) and os.path.getsize(out) > 0)
    if not os.path.exists(out):
        return
    import contract
    rec = json.loads(open(out).readline())
    hard, soft = contract.check(rec)
    check('the record satisfies the reproducibility contract', not hard, str(hard))
    for name, why in soft:
        print(f'        advisory: {name} absent -- {why}')
    check('per-document probabilities cover every test document',
          len(rec['probs']) == rec['n']['test'])
    check('per-generator block is populated', len(rec['per_generator']) >= 1,
          str(list(rec['per_generator'])))
    eff = rec['code_path']['effective_model_config']
    check('the model actually loaded with sdpa attention',
          eff['attn_implementation'] == 'sdpa', str(eff))
    check('reference_compile actually took', eff['reference_compile'] is False)
    check('classifier_pooling actually took',
          eff['classifier_pooling'] == rec['run_key']['classifier_pooling'])
    check('a full checkpoint was written mid-run',
          rec['code_path']['checkpointing']['full_state'] is True)
    check('no document was truncated at max_length',
          rec['tokenisation']['test']['n_truncated'] == 0,
          f"max tokens {rec['tokenisation']['test']['tokens_max']}")
    check('training loss is finite (no NaN from the attention path)',
          all(v == v for h in rec['log_history'] for v in h.values()
              if isinstance(v, float)))
    print(f"  smoke record: AUC {rec['test']['auc']:.4f}  "
          f"BA {rec['test']['balanced_acc']:.4f}  {rec['train_seconds']}s")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--offline', action='store_true', help='skip the real training run')
    ap.add_argument('--gpu-only', action='store_true',
                    help='skip the offline block. For Colab, where the corpus itself is '
                         'not on the VM -- only the prepared docs.jsonl/splits.json are, '
                         'so the prep-determinism check has nothing to rebuild from.')
    ap.add_argument('--exp', default=EXP)
    ap.add_argument('--model', default='answerdotai/ModernBERT-base')
    a = ap.parse_args()
    if not a.gpu_only:
        offline(a.exp)
    if not a.offline:
        gpu_run(a.exp, a.model)
    print(f"\n{'SMOKE TEST FAILED: ' + ', '.join(FAILED) if FAILED else 'ALL CHECKS PASSED'}")
    raise SystemExit(1 if FAILED else 0)


if __name__ == '__main__':
    main()
