"""Assemble the labelled corpus from the questions and the generated answers.

One row per DOCUMENT. Each question contributes exactly one human document and
exactly one ai document, so the classes are balanced 1:1 by construction rather
than by subsampling, and the pair shares a question, a topic and a length
target.

Grouping matters more here than anywhere else in the project. A human answer and
the ai answer written against it share the question, the word-count target and
the paragraph target; splitting a pair across train and test would let a model
memorise the topic and score on the test set without reading prose. Splits are
therefore assigned per QUESTION at sampling time and this script asserts that no
question's two documents ever land in different splits.

Provenance is carried on every ai row -- generator, prompt version, seed -- so
phase 4 can run model attribution on these exact documents without regenerating
anything. That is a requirement, not a convenience, and it is asserted here:
a row labelled `ai` with no model is a fatal error.

Whitespace is NOT normalised. That is a detector-side training step, deliberately
left out of the corpus so the raw text stays faithful and the normalisation can
be changed without regenerating 2,772 documents.

    python3 phase3/scripts/build_corpus.py
"""
import collections
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
QUESTIONS = f"{ROOT}/phase3/corpus/questions.jsonl"
ANSWERS = f"{ROOT}/phase3/corpus/answers.jsonl"
OUTDIR = f"{ROOT}/phase3/corpus"

# --- repair: strip any stale organisational field off the answer rows ------
# `split` was recorded at generation time and revised afterwards when the
# corpus was extended, leaving 73 rows claiming a split their question no
# longer had. The generator no longer writes it; this removes it from rows
# already on disk so nothing downstream can read it by accident. Run here
# rather than mid-sweep because rewriting a file another process is appending
# to is how the duplicate rows happened.
_q_split = {}
for line in open(QUESTIONS):
    if line.strip():
        r = json.loads(line)
        _q_split[r["id"]] = r["split"]
_rows, _stale = [], 0
for line in open(ANSWERS):
    if not line.strip():
        continue
    r = json.loads(line)
    if "split" in r:
        if r["id"] in _q_split and r["split"] != _q_split[r["id"]]:
            _stale += 1
        del r["split"]
    _rows.append(r)
with open(ANSWERS, "w") as f:
    for r in _rows:
        f.write(json.dumps(r) + "\n")
if _stale:
    print(f"repaired {_stale} answer rows whose recorded split disagreed with "
          f"the question file, and dropped the field from all {len(_rows)} rows. "
          f"Split now lives in exactly one place.")

questions = {}
for i, line in enumerate(open(QUESTIONS), 1):
    if not line.strip():
        continue
    try:
        r = json.loads(line)
    except json.JSONDecodeError as e:
        sys.exit(f"FATAL {QUESTIONS}:{i}: {e}")
    questions[r["id"]] = r

answers = {}
dupes = 0
for i, line in enumerate(open(ANSWERS), 1):
    if not line.strip():
        continue
    try:
        r = json.loads(line)
    except json.JSONDecodeError as e:
        sys.exit(f"FATAL {ANSWERS}:{i}: {e}")
    if r["id"] in answers:
        dupes += 1
    answers[r["id"]] = r
if dupes:
    print(f"NOTE: {dupes} duplicate ai rows collapsed, last wins")

missing = [q for q in questions if q not in answers]
if missing:
    print(f"WARNING: {len(missing)} questions have no ai document and are "
          f"EXCLUDED from the corpus so the classes stay paired. "
          f"First: {missing[:3]}")

docs = []
for qid, q in sorted(questions.items()):
    if qid not in answers:
        continue
    a = answers[qid]
    if a["model"] != q["model"]:
        sys.exit(f"FATAL {qid}: generated by {a['model']} but assigned "
                 f"{q['model']}. Provenance must match the assignment.")
    docs.append({"doc_id": f"{qid}-h", "question_id": qid, "q_id": q["q_id"],
                 "split": q["split"], "label": "human", "model": "human",
                 "text": q["human_answer"], "words": q["human_words"],
                 "question": q["question"], "score": q["score"],
                 "url": q["url"]})
    docs.append({"doc_id": f"{qid}-a", "question_id": qid, "q_id": q["q_id"],
                 "split": q["split"], "label": "ai", "model": a["model"],
                 "text": a["text"], "words": a["words"],
                 "question": q["question"],
                 "prompt": a.get("prompt", "floor"), "seed": a.get("seed"),
                 "target_words": a.get("target_words"),
                 "draws": a.get("draws"), "post": a.get("post")})

# --- assertions, each one a bug this project has actually shipped ----------
by_q = collections.defaultdict(set)
for d in docs:
    by_q[d["question_id"]].add(d["split"])
bad = [q for q, s in by_q.items() if len(s) > 1]
if bad:
    sys.exit(f"FATAL: {len(bad)} questions span more than one split "
             f"(first {bad[:3]}). A pair split across train and test leaks the "
             f"topic and the length target.")

texts = collections.Counter(d["text"] for d in docs)
repeats = [t for t, c in texts.items() if c > 1]
if repeats:
    sys.exit(f"FATAL: {len(repeats)} documents appear more than once. An item "
             f"count that overstates the document count is the defect that "
             f"invalidated three phase-1 figures.")

no_model = [d["doc_id"] for d in docs if d["label"] == "ai" and not d["model"]]
if no_model:
    sys.exit(f"FATAL: {len(no_model)} ai documents carry no generator. "
             f"Provenance is a requirement -- phase 4 attribution reuses these "
             f"exact documents.")

os.makedirs(OUTDIR, exist_ok=True)
with open(f"{OUTDIR}/dataset.jsonl", "w") as f:
    for d in docs:
        f.write(json.dumps(d) + "\n")
for s in ("train", "dev", "test"):
    with open(f"{OUTDIR}/{s}.jsonl", "w") as f:
        for d in docs:
            if d["split"] == s:
                f.write(json.dumps(d) + "\n")

print(f"\n{len(docs)} documents over {len(by_q)} questions -> {OUTDIR}/dataset.jsonl")
print(f"{'split':<8} {'docs':>6} {'human':>6} {'ai':>6} {'words (median)':>16}")
for s in ("train", "dev", "test"):
    sub = [d for d in docs if d["split"] == s]
    hu = [d for d in sub if d["label"] == "human"]
    ai = [d for d in sub if d["label"] == "ai"]
    wh = sorted(d["words"] for d in hu)
    wa = sorted(d["words"] for d in ai)
    print(f"{s:<8} {len(sub):>6} {len(hu):>6} {len(ai):>6}   "
          f"human {wh[len(wh)//2] if wh else 0}, ai {wa[len(wa)//2] if wa else 0}")

# Per-generator is the headline for this corpus, never a pooled rate. A single
# Haiku pass over the floor output ran 7% to 80% detection across the seven
# generators; the pooled 26.7% describes none of them, and a detector trained on
# the mix will report whatever its evaluation slice happens to over-weight.
print(f"\nai documents by generator "
      f"(ALWAYS report per-generator beside any aggregate):")
c = collections.Counter(d["model"] for d in docs if d["label"] == "ai")
for m, n in sorted(c.items()):
    per = collections.Counter(d["split"] for d in docs
                              if d["label"] == "ai" and d["model"] == m)
    print(f"  {m:<32} {n:>5}   " +
          " ".join(f"{s} {per[s]}" for s in ("train", "dev", "test")))
