"""Judge single-document batches over the OpenRouter API, one fresh call each.

The instruction text is identical to what a subagent judge is given, so the two
routes differ only in transport. That is the point: phase 1's published numbers
came from Claude Code subagent judges, and if API judges are a different
instrument then no phase-3 number is comparable to a phase-1 number.

    python3 phase3/scripts/judge_api.py BATCH_DIR OUT_DIR --model anthropic/claude-haiku-4.5

Writes OUT_DIR/pred_NN.json in the format phase1/scripts/14_score_single.py reads.
"""
import argparse
import glob
import json
import os
import random
import re
import sys
import time
from concurrent.futures import ThreadPoolExecutor

import requests

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ENDPOINT = "https://openrouter.ai/api/v1/chat/completions"

INSTRUCTION = """You are given a small set of comments from the subreddit r/explainlikeimfive. Each was either written by a human redditor between 2011 and 2019, or generated by a language model in 2026 imitating that style.

Judge each comment on its own. There is no reference text, no fixed proportion of human to AI, and the comments are unrelated to each other.

Reply with JSON and nothing else, in exactly this form:

{"predictions": [{"item": "I000", "verdict": "ai", "confidence": "high", "reason": "a short phrase naming the cue you used"}]}

verdict is "ai" or "human". confidence is "low", "medium" or "high". Include every item you were given, in order."""


def load_key():
    if os.environ.get("OPENROUTER_API_KEY"):
        return os.environ["OPENROUTER_API_KEY"]
    for path in (f"{ROOT}/phase1/.env", f"{ROOT}/.env"):
        if os.path.exists(path):
            for line in open(path):
                k, _, v = line.partition("=")
                if k.strip() == "OPENROUTER_API_KEY":
                    return v.strip().strip("'\"")
    sys.exit("FATAL: OPENROUTER_API_KEY not found")


def extract(text):
    """Pull the JSON object out of a reply. Fails loudly: phase 1 lost ten items
    to a scorer that skipped an unparseable prediction file in silence."""
    m = re.search(r"\{.*\}", text, re.S)
    if not m:
        raise ValueError(f"no JSON object in reply: {text[:200]}")
    return json.loads(m.group(0))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("batch_dir")
    ap.add_argument("out_dir")
    ap.add_argument("--model", default="anthropic/claude-haiku-4.5")
    ap.add_argument("--pass-tag", default="")
    ap.add_argument("--workers", type=int, default=8)
    ap.add_argument("--retries", type=int, default=5)
    ap.add_argument("--temperature", type=float, default=1.0)
    a = ap.parse_args()

    batches = sorted(glob.glob(f"{a.batch_dir}/batch_*.txt"))
    if not batches:
        sys.exit(f"FATAL: no batch_*.txt in {a.batch_dir}")
    os.makedirs(a.out_dir, exist_ok=True)
    key = load_key()
    headers = {"Authorization": f"Bearer {key}", "Content-Type": "application/json"}
    usage = {"in": 0, "out": 0}
    fails = []

    def judge(path):
        n = os.path.basename(path).split("_")[1].split(".")[0]
        out_path = f"{a.out_dir}/pred_{a.pass_tag}{n}.json"
        if os.path.exists(out_path):
            return
        body = open(path).read()
        payload = {"model": a.model, "temperature": a.temperature,
                   "max_tokens": 2000,
                   "messages": [{"role": "system", "content": INSTRUCTION},
                                {"role": "user", "content": body}]}
        last = None
        for attempt in range(a.retries):
            try:
                r = requests.post(ENDPOINT, headers=headers, json=payload, timeout=180)
                if r.status_code == 429:
                    time.sleep(float(r.headers.get("Retry-After") or 0) or min(60, 5 * 2 ** attempt))
                    raise RuntimeError("429")
                if r.status_code == 402:
                    sys.exit("FATAL: 402 Payment Required. Stopping the run.")
                r.raise_for_status()
                d = r.json()
                obj = extract(d["choices"][0]["message"]["content"] or "")
                if not obj.get("predictions"):
                    raise ValueError("no predictions in object")
                json.dump(obj, open(out_path, "w"), indent=1)
                u = d.get("usage", {})
                usage["in"] += u.get("prompt_tokens", 0)
                usage["out"] += u.get("completion_tokens", 0)
                return
            except Exception as e:
                last = e
                time.sleep((2 ** attempt) + random.random())
        fails.append((path, str(last)))
        print(f"FAIL {path}: {last}", file=sys.stderr)

    with ThreadPoolExecutor(max_workers=a.workers) as ex:
        list(ex.map(judge, batches))
    print(f"{len(batches) - len(fails)}/{len(batches)} batches judged by "
          f"{a.model} -> {a.out_dir}", file=sys.stderr)
    print(f"tokens in {usage['in']:,} out {usage['out']:,}", file=sys.stderr)
    if fails:
        sys.exit(f"FATAL: {len(fails)} batches failed. Not scoring a short set.")


if __name__ == "__main__":
    main()
